# Generated by Django 6.0.6 on 2026-07-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(help_text='Comma-separated list of author names.')),
                ('title', models.CharField(help_text='Full title of the paper / book chapter.', max_length=512)),
                ('journal', models.CharField(help_text='Journal name, volume, and issue info.', max_length=512)),
                ('year', models.CharField(help_text="Four-digit publication year (stored as text to allow '2024–25').", max_length=10)),
                ('link', models.URLField(blank=True, default='', help_text='DOI link or full URL to the published paper.', max_length=2048)),
                ('publisher', models.CharField(blank=True, default='', help_text='Publisher tag, e.g. IEEE, Elsevier, Springer.', max_length=256)),
                ('impact', models.CharField(blank=True, default='', help_text="Impact factor indicator value, e.g. '4.7'.", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-created_at'],
            },
        ),
    ]
